### ISSUE TITLE
缺少build tool 24.0.0 rc3

### ISSUE THREAD

**Issue by onionYJK** [YiuChoi/MicroReader#20]
请问 你是怎么更新的呢？有什么软件推荐吗？SDK manager连不上网络。

**Comment by YiuChoi** [comment]
我是翻墙的，作为android程序员，翻墙是基础技能了

**Comment by onionYJK** [comment]
嗯，然后我也翻墙了，用Shadowsocks这个工具，但是，我看到的build tools 版本是23.0.3 没有24.0.0呢，是我没翻成功么，但是我能打开google哒。

**Comment by YiuChoi** [comment]
@onionYJK 你可以修改成你本地有的版本

**Comment by MaiPingHongCha** [comment]
为什么总是这个错误啊Error:failed to find Build Tools revision 24.0.0 rc3
Install Build Tools 24.0.0 rc3 and sync project

**Comment by YiuChoi** [comment]
@MaiPingHongCha 修改成你自己有的版本呗

**Comment by MaiPingHongCha** [comment]
@YiuChoi 我换成Build Tools 24.0.0 rc4,然后又报错：The project 'MicroReader-master' may be using a version of Gradle that does not contain the method.接着按网上的方法把android的什么配置删除重新Gradle,又回到failed to find Build Tools revision 24.0.0 rc3.请问怎么解决

**Comment by lxykad** [comment]
缺少build tool 24.0.0 rc3 同样是这个错误，翻墙什么的都不行，修改自己的版本后还是这个错。

**Comment by YiuChoi** [comment]
app和swipeback两个地方都改了吗 @MaiPingHongCha @lxykad

**Comment by MaiPingHongCha** [comment]
@YiuChoi 好了，谢谢哈。另外，大神能不能加你微信。或者你加我PSY7365903
