### ISSUE TITLE
运行报错(Mac)

### ISSUE THREAD

**Issue by gh4work** [YiuChoi/MicroReader#6]
编译没有问题，运行的时候报错：Error:objc[31435]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

**Comment by YiuChoi** [comment]
这个是你编译环境或者运行环境的问题吧，这报错说的也是Java虚拟机的问题呀

**Comment by xiuweikang** [comment]
http://stackoverflow.com/questions/18794573/objc10012-class-javalaunchhelper-is-implemented-in-both-libinstrument-dyl

**Comment by huangyk** [comment]
Error:java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0,,后面还有错,,哎,,这么好的项目

**Comment by SivanLiu** [comment]
可以通过设置系统java环境变量来解决，这个可以用jenv来实现，具体请参考：
http://boxingp.github.io/blog/2015/01/25/manage-multiple-versions-of-java-on-os-x/
