### ISSUE TITLE
刷新和加载都不能完成.

### ISSUE THREAD

**Issue by toyluck** [YiuChoi/MicroReader#7]
![a7ce6ffe-3a86-457e-ad43-ed3f84a4d676](https://cloud.githubusercontent.com/assets/13290492/15034166/5cf623e4-12a5-11e6-9e1c-23513264e15f.png)
![image](https://cloud.githubusercontent.com/assets/13290492/15034231/fbcc5f4c-12a5-11e6-89d2-f2fd784d3e9c.png)

进入详情页面,返回列表就刷新或者加载更多不能结束.用的是 官方2.0的模拟器 4.1版本.

![image](https://cloud.githubusercontent.com/assets/13290492/15034211/cc6ff3ee-12a5-11e6-8112-d343f318c40e.png)
当加载更多不能结束时,上拉到顶,不能显示完整的item

**Comment by YiuChoi** [comment]
感谢，已修复。
