### ISSUE TITLE
作者你好，提个问题给你

### ISSUE THREAD

**Issue by AndroidJiang** [YiuChoi/MicroReader#9]
.addNetworkInterceptor(REWRITE_CACHE_CONTROL_INTERCEPTOR)还要再添加应用拦截器，否则测试离线缓存是无效的，离线缓存一直都存在，设置的时间你可以改成60s或者30s试一下，会发现时间到了之后，它还会显示在上面，所以上面的离线缓存毫无意义，我测试后发现再加上普通拦截器就生效了，具体原因两者区别我也不大理解，希望作者测试一下。或者查看我之前写的一篇文章http://blog.csdn.net/qqyanjiang/article/details/51316116

**Comment by YiuChoi** [comment]
我开发的时候确实遇到这个问题，前面的60s在线缓存有用，后面的离线缓存没有，所以我就自己写了个缓存

**Comment by YiuChoi** [comment]
@AndroidJiang 
添加了.addInterceptor(cacheInterceptor)之后确实可以离线缓存了，非常感谢！
